name: Update Package Version
on:
  push:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Python Tests
        uses: platomo/test-python-app-action@748a9663eb55bb8abbee914374b743f039c0cb7d
        with:
          os: linux-latest
          py-version: 3.11
          test_path: ./test