name: Update Package Version

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Python package version
        uses: platomo/update-version-py-action
        with:
          version: "1.0.0.0"
          file-path: "my_package"